### ISSUE TITLE
Incorrect content-type text/html for metadata

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SCZ-deploy#2]
Metadata at https://proxy.test.scz.lab.surf.nl/md/frontend.xml is served as text/html instead of application/xml

**Comment by mrvanes** [comment]
This is tough to fix since the metadata is served by a blind fopen-read logic.

**Comment by baszoetekouw** [comment]
Ok, then the proper way to fix this is to let the metadata server serve it, via a regular webbrowser.  We have to rearrange the metadata flow anyway, so I guess that will be fixed automatically.

**Comment by mrvanes** [comment]
https://github.com/SURFscz/SCZ-deploy/blob/martin/roles/metadata/templates/create_metadata
https://meta.test.scz.lab.surf.nl/proxy_idp.xml
