### ISSUE TITLE
OIDC-op in vm verandert steeds sub van admin gebruiker

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SCZ-deploy#275]
Bij elke install/deploy/maandstand verandert de sub van de admin user van oidc-op in de vm.  Hij lijkt een random salt te gebruiken voor de hashing (zie https://oidcop.readthedocs.io/en/latest/contents/conf.html#session-params)

Weet niet of het mogelijk is om de hele hashing uit te zetten (zodat de sub gewoon `admin0001` wordt), maar anders graag iig een fixed salt per environment implementeren.

**Comment by mrvanes** [comment]
Vraag uitgezet bij Roland, want wij hebben geen "session_params" params key in onze CI config.

**Comment by mrvanes** [comment]
Fixed in https://github.com/SURFscz/SCZ-deploy/pull/276
