### ISSUE TITLE
Make COmanage entityid configurable

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SCZ-deploy#69]
COmanage's entiyid is used in multiple places, which can lead to issues like #68 
It might be better to define the entityid as a variable, and fix it in mellon using MellonSPentityId.

**Comment by baszoetekouw** [comment]
Same holds for the satosa entityids, whcih are used in multiple places (at least within satosa and in the pyff_metadata_extra surfconext url)

**Comment by mrvanes** [comment]
Satosa entityID's are not dynamic, they are fixed in conf. So I don't expect surprises there.
