### ISSUE TITLE
Test-sp needs redirect

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SCZ-deploy#7]
The test-sp needs a redirect from the root to /simplesamlphp/

**Comment by baszoetekouw** [comment]
Of beter: een landingpagina waar je kan kiezen voor OIDC of SAML login.

**Comment by baszoetekouw** [comment]
Correction, redirect needs to be to /saml

**Comment by mrvanes** [comment]
Zowel de oidc-test als sp-test root landingpage geven nu een keuze naar de sp-test en oidc-test pagina.
