### ISSUE TITLE
make sure ansible-playbook --check is able to run

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SCZ-deploy#71]
ansible-playbook --check fails on a number of places, because of inter-task dependencies via stdout variables.  This is unfortunate, and can be easily avoided.  

At least the following places are a problem:
 - ldap: generation of hash of ldap password: handle inline or store crypted hash in groupvars
 - auth_mellon: creation of base PEM cert for metadata (sp_cert), which seems unused atm

**Comment by mrvanes** [comment]
fatal: [sandbox1.vm.scz-vm.net]: FAILED! => changed=false 
  msg: python-apt must be installed to use check mode. If run normally this module can auto-install it.

**Comment by baszoetekouw** [comment]
Interesting...  I'v added python-apt as an explicit dependency in the apt task (see f3379e5d9edfb1a64cc40882f48b2f7e53857242)

**Comment by baszoetekouw** [comment]
Nou, dit werkt inmiddels al eventjes ;)
